### PR TITLE
chore: Update Create Check

### PR DESCRIPTION
**Pull request by therynamo**
Updates from https://github.com/hipstersmoothie/create-check/pull/143

### CODE REVIEW

**Review by AndersDJohnson — APPROVED** [review]
📖 💯 🚀 !

**Review by hipstersmoothie — APPROVED** [review]

**Comment by therynamo** [comment]
Thanks for approving @hipstersmoothie ! Any chance we could get a release this morning when you're free?

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v1.0.2`](https://github.com/hipstersmoothie/jest-github-reporter/releases/tag/v1.0.2) :rocket:

**Comment by therynamo** [comment]
Hey @hipstersmoothie this worked like a charm!

**Pull request merged**
